export const ResponseMessage = {
  USER_DOES_NOT_EXISTS_WITH_GIVEN_WALLET_ADDRESS: "User with given wallet Address doesn't exists",
  USER_DOES_NOT_EXISTS_WITH_GIVEN_USERNAME: "User with given username doesn't exists",
  USER_EXISTS_WITH_GIVEN_EMAIL_ADDRESS: 'User with the given email address already exists',
  USER_EXISTS_WITH_GIVEN_WALLET: 'User with given wallet address already exists',
  USER_DATA_ALREADY_EXIST: 'User wallet address, unique id and hashed mnenomic already exists',
  USER_DATA_UPDATED: 'User data updated',
  ADMIN_EXISTS_WITH_GIVEN_EMAIL_ADDRESS: 'Admin with the given email address already exists',
  INTERNAL_SERVER_ERROR: 'Internal Server Error',
  BAD_REQUEST: 'Bad Request',
  UNAUTHORIZED: 'Unauthorized',
  USER_CREATED: 'User has been created',
  USER_LOGGED_IN: 'User has been Logged In',
  NOT_FOUND: 'logged in user details not found',
  EMAIL_NOT_VERIFIED: 'Email not verified',
  EMAIL_VERIFIED: 'Email verified',
  OTP_Expired: 'OTP Expired',
  OTP_VERIFICATION: 'OTP Verified successfully',
  OTP_GENERATED: 'A OTP has generated, it will expires in 5 minute',
  OTP_NOT_MATCHED: 'OTP not matched',
  INVALID_CRED: 'Invalid credentials',
  LOGGED_IN_ADMIN: 'Get data about current logged in admin',
  ALL_ADMINS: 'get all Admins',
  UPDATE_ADMIN: 'Update Admin Data',
  ADMIN_NOT_FOUND: 'Admin not found**',
  ADMIN_CREATED: 'Admin created',
  ADMIN_LOGGED_IN: 'Admin logged in',
  USER_BANNED: 'User has been banned from platform',
  USER_BLOCKED: 'User has been blocked',
  EMAIL_SUBJECT_NEW_ACOUNT: `Welcome to Your PicoWallet! Please verify your Your PicoWallet account`,
  EMAIL_SUBJECT_OTP_VERIFICATION: `Please verify your Your PicoWallet account`,
  EMAIL_SUBJECT_PASSWORD_RESET: `Change your password`,
  PASSWORD_RESET: 'Password reset successful',
  PASSWORD_UPDATE_FAILED: 'Updating password failed, Kindly retry',
  USER_DATA_FETCHED: 'User data fetched',
  INVALID_CRED_OR_TOKEN_EXPIRED: 'Invalid credentials or token expired',
  UNIQUE_CONSTRAINT: 'Either unique_id or wallet_address is voilating unique constraint',
  ONLINE_MODE_ACTIVATED: 'Online mode activated',
  OFFLINE_MODE_ACTIVE: 'Offline mode activated',
  DATA_UPDATED: 'Data updated successful',
  ERROR_DATA_UPDATED: 'Error on data updation',
  DATA_CREATED: 'Data created successfully',
  DATA_FETCHED: 'Data fetched successfully',
  DATA_DELETED: 'Data deleted successfully',
  DATA_DELETE_NOT_ALLOWED: 'Data delete not allowed',
  DATA_NOT_FOUND: 'Data not found',
  SAME_PASSWORDS: 'password is same as previous password, kindly create a new one',
  DATA_ALREADY_EXIST: 'Data already exists',
  UPDATE_NOT_ALLOWED: 'Update not allowed',
  DELETE_NOT_ALLOWED: 'Delete not allowed',
  WALLET_NOT_CREATED: 'Wallet not created'
};
